# Dynamic inventory for AWS EC2 instances
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  tag:Project: cistechhub
  instance-state-name: running

hostnames:
  - ip-address
  - dns-name

compose:
  ansible_host: public_ip_address
  ansible_user: "'ec2-user'"

keyed_groups:
  - key: tags.Environment
    prefix: env
  - key: tags.Name
    separator: ""
